### ISSUE TITLE
incompatible with rails 2.3.*

### ISSUE THREAD

**Issue by lsmolic** [esmarkowski/tampon#4]
Rails::Railtie does not exist until rail 3.0.0

not sure if the functionality still works, but you can change this:

module Tampon
  require 'railtie' if defined?(Rails)
end

to this:

module Tampon
  require 'railtie' if defined? ::Rails::Railtie
end

and at least it won't break rails 2.3.*

**Comment by esmarkowski** [comment]
This is no longer used in capistrano-tampon 3.0.0
